<a href="https://colab.research.google.com/github/Bartenderr/lotto_prediction/blob/main/metro_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORT DEPENDENCIES FOR THIS ML PROJECT 

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import LSTM, Dense, Bidirectional, Dropout


Load data set into Data frame

In [4]:
df = pd.read_csv('/content/drive/MyDrive/metro_full_result.csv')
df

Date  WN1  WN2  WN3  WN4  WN5  MAN1  MAN2  MAN3  MAN4  MAN5   Time
0     1/30/2017   42   56   47   43   51   NaN   NaN   NaN   NaN   NaN  19:45
1    02/03/2017   67   83   76   41   46   NaN   NaN   NaN   NaN   NaN  12:45
2    02/06/2017    5   12   61   89   28   NaN   NaN   NaN   NaN   NaN  19:45
3    02/10/2017    4   75    2   13   24   NaN   NaN   NaN   NaN   NaN  12:45
4     2/13/2017   64    8   77   69   22   NaN   NaN   NaN   NaN   NaN  19:45
..          ...  ...  ...  ...  ...  ...   ...   ...   ...   ...   ...    ...
617  01/09/2023   69   14   58   45   48   NaN   NaN   NaN   NaN   NaN    NaN
618  01/13/2023   39   89   51   11   53   NaN   NaN   NaN   NaN   NaN    NaN
619  01/16/2023   36   14   46   34   33   NaN   NaN   NaN   NaN   NaN    NaN
620  01/20/2023   35   37    5   15   39   NaN   NaN   NaN   NaN   NaN    NaN
621  01/23/2023   42   51   54   46   61   NaN   NaN   NaN   NaN   NaN    NaN

[622 rows x 12 columns]

In [7]:
df.drop(["Date", "MAN1", "MAN2", "MAN3", "MAN4", "MAN5", "Time"], axis=1, inplace=True)

In [8]:
df.head()

WN1  WN2  WN3  WN4  WN5
0   42   56   47   43   51
1   67   83   76   41   46
2    5   12   61   89   28
3    4   75    2   13   24
4   64    8   77   69   22

In [ ]:
df.info()

In [ ]:
df.tail()

In [ ]:
df.describe()

In [ ]:
df.shape

re-scale data

In [ ]:
scaler = StandardScaler().fit(df.values)
transformed_dataset = scaler.transform(df.values)
transformed_df = pd.DataFrame(data=transformed_dataset, index=df.index)

In [ ]:
#Check_out scaled data 
transformed_df.head()

Define variables 

In [ ]:
number_of_rows = df.values.shape[0]
number_of_rows

621

In [ ]:
#AMOUNT OF GAMES WE NEED TO TAKE INTO CONSIDERATION
window_length = 7
window_length

In [ ]:
#BALLS COUNT 

In [ ]:
number_of_features = df.values.shape[1]
number_of_features

Create X and y for each rowin our scaled data.

In [ ]:
#it should have the format for keras LTSM model(rows, window size, balls)
X = np.empty([number_of_rows - window_length, window_length, number_of_features], dtype=float)

y = np.empty([number_of_rows - window_length, number_of_features], dtype=float)

for i in range(0, number_of_rows-window_length):
  X[i] = transformed_df.iloc[i : i+window_length, 0 : number_of_features]
  y[i] = transformed_df.iloc[i+window_length : i+window_length+1, 0 : number_of_features]

In [ ]:
X.shape

(614, 7, 5)

In [ ]:
y.shape

(614, 5)

In [ ]:
X[0]

array([[-0.09789613,  0.46886285,  0.04151785, -0.12023674,  0.24615676],
       [ 0.86463551,  1.51066292,  1.15914867, -0.19829948,  0.05640583],
       [-1.52244297, -1.22888542,  0.58106377,  1.67520634, -0.62669752],
       [-1.56094423,  1.20198141, -1.69273687, -1.29117788, -0.77849826],
       [ 0.74913171, -1.38322617,  1.19768767,  0.89457892, -0.85439864],
       [ 0.82613425,  0.70037397, -1.53858089,  0.23104561,  0.701559  ],
       [ 0.59512665,  1.16339623, -1.46150291,  0.46523383, -1.53750199]])

In [ ]:
y[0]

array([-1.52244297,  1.47207773,  1.04353169,  0.69942206, -1.27185068])

In [ ]:
X[1]

array([[ 0.86463551,  1.51066292,  1.15914867, -0.19829948,  0.05640583],
       [-1.52244297, -1.22888542,  0.58106377,  1.67520634, -0.62669752],
       [-1.56094423,  1.20198141, -1.69273687, -1.29117788, -0.77849826],
       [ 0.74913171, -1.38322617,  1.19768767,  0.89457892, -0.85439864],
       [ 0.82613425,  0.70037397, -1.53858089,  0.23104561,  0.701559  ],
       [ 0.59512665,  1.16339623, -1.46150291,  0.46523383, -1.53750199],
       [-1.52244297,  1.47207773,  1.04353169,  0.69942206, -1.27185068]])

In [ ]:
y[1]

array([-0.48290879, -1.30605579, -0.65218404,  0.11395149,  1.53646309])

In [ ]:
#MODELING

In [ ]:
model = Sequential()

In [ ]:
model.add(Bidirectional(LSTM(240, input_shape =(window_length, number_of_features), return_sequences = True)))

In [ ]:
#dropout layers in order to reduce overfitting
model.add(Dropout(0.2))

In [ ]:
#Add a Second LSTM layer

In [ ]:
model.add(Bidirectional(LSTM(240, input_shape =(window_length, number_of_features), return_sequences = True)))

In [ ]:
#dropout again 
model.add(Dropout(0.2))

In [ ]:
#Add a third LSTM layer

In [ ]:
model.add(Bidirectional(LSTM(240, input_shape =(window_length, number_of_features), return_sequences = True)))

In [ ]:
#Dropout again thrid time

In [ ]:
model.add(Dropout(0.2))

In [ ]:
#add a Fourth Layer of LSTM
model.add(Bidirectional(LSTM(240, input_shape =(window_length, number_of_features), return_sequences = False)))

In [ ]:
#Add Dense Layer 
model.add(Dense(number_of_features))

In [ ]:
#Compile the RNN

In [ ]:
from tensorflow import keras
from tensorflow.keras.optimizers import Adam

model.compile(optimizer=Adam(learning_rate=0.0001), loss='mse', metrics=['accuracy'])


In [ ]:
model.fit(x=X, y=y, batch_size=100, epochs=300, verbose=2)

Epoch 1/300
7/7 - 28s - loss: 0.9996 - accuracy: 0.1922 - 28s/epoch - 4s/step
Epoch 2/300
7/7 - 5s - loss: 0.9985 - accuracy: 0.2313 - 5s/epoch - 661ms/step
Epoch 3/300
7/7 - 5s - loss: 0.9975 - accuracy: 0.2068 - 5s/epoch - 669ms/step
Epoch 4/300
7/7 - 5s - loss: 0.9966 - accuracy: 0.2199 - 5s/epoch - 659ms/step
Epoch 5/300
7/7 - 5s - loss: 0.9951 - accuracy: 0.2345 - 5s/epoch - 655ms/step
Epoch 6/300
7/7 - 5s - loss: 0.9931 - accuracy: 0.2231 - 5s/epoch - 669ms/step
Epoch 7/300
7/7 - 5s - loss: 0.9923 - accuracy: 0.2280 - 5s/epoch - 661ms/step
Epoch 8/300
7/7 - 5s - loss: 0.9917 - accuracy: 0.2427 - 5s/epoch - 662ms/step
Epoch 9/300
7/7 - 5s - loss: 0.9912 - accuracy: 0.2410 - 5s/epoch - 657ms/step
Epoch 10/300
7/7 - 8s - loss: 0.9897 - accuracy: 0.2231 - 8s/epoch - 1s/step
Epoch 11/300
7/7 - 5s - loss: 0.9892 - accuracy: 0.2378 - 5s/epoch - 672ms/step
Epoch 12/300
7/7 - 5s - loss: 0.9891 - accuracy: 0.2410 - 5s/epoch - 663ms/step
Epoch 13/300
7/7 - 5s - loss: 0.9879 - accuracy: 0.23

In [ ]:
to_predict = df.tail(8)
to_predict

A   B   C   D   E
613  71  44  14  63  84
614  23  79  73  39  33
615  70  44  42  64   1
616  47  26  36   7  84
617  69  14  58  45  48
618  39  89  51  11  53
619  36  14  46  34  33
620  35  37   5  15  39

In [ ]:
to_predict.drop([to_predict.index[-1]], axis=0, inplace=True)

In [ ]:
to_predict


A   B   C   D   E
613  71  44  14  63  84
614  23  79  73  39  33
615  70  44  42  64   1
616  47  26  36   7  84
617  69  14  58  45  48
618  39  89  51  11  53
619  36  14  46  34  33

In [ ]:
prediction=df.tail(1)
prediction

A   B  C   D   E
620  35  37  5  15  39

In [ ]:
to_predict = np.array(to_predict)
to_predict

array([[71, 44, 14, 63, 84],
       [23, 79, 73, 39, 33],
       [70, 44, 42, 64,  1],
       [47, 26, 36,  7, 84],
       [69, 14, 58, 45, 48],
       [39, 89, 51, 11, 53],
       [36, 14, 46, 34, 33]])

In [ ]:
scaled_to_predict = scaler.transform(to_predict)
scaled_to_predict

array([[ 1.01864057,  0.00584059, -1.23026894,  0.66039069,  1.49851291],
       [-0.82942018,  1.35632216,  1.04353169, -0.27636222, -0.43694659],
       [ 0.98013931,  0.00584059, -0.15117712,  0.69942206, -1.65135255],
       [ 0.0946102 , -0.68869279, -0.38241108, -1.5253661 ,  1.49851291],
       [ 0.94163804, -1.15171504,  0.46544679, -0.04217399,  0.1323062 ],
       [-0.21339993,  1.74217404,  0.19567383, -1.36924062,  0.32205714],
       [-0.32890373, -1.15171504,  0.00297886, -0.47151908, -0.43694659]])

In [ ]:
y_pred = model.predict(np.array([scaled_to_predict]))

print('The predicted numbers in the last lottery game are:', scaler.inverse_transform(y_pred).astype(int)[0])

1/1 [==============================] - 0s 32ms/step
The predicted numbers in the last lottery game are: [37 28  2 26 54]


In [ ]:
prediction = np.array(prediction)

print('The actual numbers int the last lottery game were:', prediction[0])

The actual numbers int the last lottery game were: [35 37  5 15 39]


In [ ]:
##change data set next time
##see what the other guy tuned
##play with the epochs try 519

In [ ]:
##increanse the window_length